### PR TITLE
Add FAQ page

### PR DESCRIPTION
**Pull request by nickskyline**
Initial FAQ page, implemented in download section.

This is how it looks in downlaods section.

imagen

And this is how the page looks like.

imagen

imagen

### CODE REVIEW

**Comment by BGMP** [comment]
@nickskyline Mind posting a few screenshots please? I think I'm currently rebasing the i18n stuff

**Comment by nickskyline** [comment]
@BGMP Done!

**Review by BGMP — CHANGES_REQUESTED** [review]
I think first and for most we should compress the content somehow. Maybe an accordion to make it a bit more digestible?

See https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example

**Comment by BGMP** [comment]
I made a few changes, let me know what you think @nickskyline

**Review by BGMP — APPROVED** [review]
This is good enough imo, but it's your call @nickskyline . I'll merge when you leave your final comments.

**Comment by nickskyline** [comment]
Seems good to me @BGMP. The only drawback was the position of the faq box, but I think with the new wording it now makes a lot of sense to the organization of the page, so.... Go ahead!

**Pull request merged**
